package project02;

import javax.swing.JOptionPane;

/**
 *
 * @author BCMedia
 */
public class BukuTeman extends javax.swing.JFrame {
    dtAlamat DA = new dtAlamat(0);
    
    private void cmdNav(boolean jns){
        cNext.setEnabled(jns);
        cPrev.setEnabled(jns);
    }
    private void cmdTambah(boolean jns){
        cTambah.setEnabled(jns);
    }
    private void StoreData(){
        DA.StoreData(txNama.getText(), txAlamat.getText(), txTelp.getText());
    }
    private void cmdUbah(boolean jns){
        cUbah.setEnabled(jns);
    }
    private void cmdHapus(boolean jns){
        cHapus.setEnabled(jns);
    }
    private void ViewData(int aRec){
        aRec--;
        txNama.setText(DA.GetViewNama(aRec));
        txAlamat.setText(DA.GetViewAlamat(aRec));
        txTelp.setText(DA.GetViewNoTelp(aRec));
        posRec();
    }
    private void edtext(boolean jns){
        txNama.setEditable(jns);
        txAlamat.setEditable(jns);
        txTelp.setEditable(jns);
    }
    private void posRec(){
        LBJREK.setText(String.valueOf(DA.aRec));
        LBREC.setText(String.valueOf(DA.Rec));
    }
    private void clearform(){
        txNama.setText("");
        txAlamat.setText("");
        txTelp.setText("");
    }
    private void loadata(){
        edtext(false);
        cmdNav(false);
        cmdTambah(true);
        cmdUbah(false);
        cmdHapus(false);
        if(DA.aRec>0){
            ViewData(1);
            cmdNav(true);
            cmdTambah(true);
            cmdUbah(true);
            cmdHapus(true);
            posRec();
        }
    }
    /**
     * Creates new form BukuTeman
     */
    public BukuTeman() {
        initComponents();
        loadata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txAlamat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txTelp = new javax.swing.JTextField();
        cPrev = new javax.swing.JButton();
        cNext = new javax.swing.JButton();
        cTambah = new javax.swing.JButton();
        cUbah = new javax.swing.JButton();
        cHapus = new javax.swing.JButton();
        cSelesai = new javax.swing.JButton();
        LBJREK = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LBREC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(400, 330));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Buku Teman");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nama");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Alamat");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("No Telp");

        cPrev.setText("<");
        cPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cPrevActionPerformed(evt);
            }
        });

        cNext.setText(">");
        cNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cNextActionPerformed(evt);
            }
        });

        cTambah.setText("Tambah");
        cTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTambahActionPerformed(evt);
            }
        });

        cUbah.setText("Ubah");

        cHapus.setText("Hapus");

        cSelesai.setText("  Selesai");
        cSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cSelesaiActionPerformed(evt);
            }
        });

        LBJREK.setText("0");

        jLabel6.setText("/");

        LBREC.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LBREC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LBJREK))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                                    .addComponent(cNext, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txTelp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                                        .addComponent(txAlamat, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txNama, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel3)))
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LBJREK)
                        .addComponent(jLabel6)
                        .addComponent(LBREC)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cNext, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(46, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTambahActionPerformed
        if(cTambah.getText().equals("Tambah")){
            System.out.println("ARek: "+DA.aRec+"; JRek: "+DA.getJREC());
            if(DA.aRec+1 > DA.getJREC()){
                JOptionPane.showMessageDialog(null, "Data sudah penuh");
            }else{
                cTambah.setText("Simpan");
                clearform();
                cmdNav(false);
                cmdUbah(false);
                cmdHapus(false);
                edtext(true);
            }
        }else{
            cTambah.setText("Tambah");
            edtext(false);
            StoreData();
            cmdNav(true);
            cmdUbah(true);
            cmdHapus(true);
            posRec();
            ViewData(DA.aRec);
        }
    }//GEN-LAST:event_cTambahActionPerformed

    private void cPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cPrevActionPerformed
        if(DA.Rec>1){
            DA.Rec--;
            System.out.println(DA.Rec);
        }
        ViewData(DA.Rec);
    }//GEN-LAST:event_cPrevActionPerformed

    private void cNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cNextActionPerformed
        if(DA.Rec<DA.aRec){
            DA.Rec++;
            System.out.println(DA.Rec);
        }
        ViewData(DA.Rec);
    }//GEN-LAST:event_cNextActionPerformed

    private void cSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cSelesaiActionPerformed
        dispose();
    }//GEN-LAST:event_cSelesaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BukuTeman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BukuTeman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BukuTeman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BukuTeman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BukuTeman().setVisible(true); 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBJREK;
    private javax.swing.JLabel LBREC;
    private javax.swing.JButton cHapus;
    private javax.swing.JButton cNext;
    private javax.swing.JButton cPrev;
    private javax.swing.JButton cSelesai;
    private javax.swing.JButton cTambah;
    private javax.swing.JButton cUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txAlamat;
    private javax.swing.JTextField txNama;
    private javax.swing.JTextField txTelp;
    // End of variables declaration//GEN-END:variables

    
}
